import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { AppState } from "./types";
import { fmtDate, fmtINR, dayKey } from "./format";
import { pendingForFarmer } from "./store";
import { HINDI_FONT_BASE64 } from "./hindi-font";

function createPdfDoc(): jsPDF {
  const doc = new jsPDF();
  // Register Hind Devanagari font in Virtual File System (VFS)
  doc.addFileToVFS("Hind.ttf", HINDI_FONT_BASE64);
  doc.addFont("Hind.ttf", "Hind", "normal");
  doc.setFont("Hind");
  return doc;
}

function header(doc: jsPDF, state: AppState, title: string, subtitle?: string) {
  doc.setFont("Hind");
  doc.setFontSize(18);
  doc.setTextColor(31, 138, 76);
  doc.text("Khetbook", 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Tractor Operator Ledger", 14, 22);
  doc.setFontSize(14);
  doc.setTextColor(20);
  doc.text(title, 14, 32);
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(subtitle, 14, 38);
  }
  if (state.settings.userName) {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Operator: ${state.settings.userName}`, 14, 44);
  }
  doc.setDrawColor(220);
  doc.line(14, 48, 196, 48);
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("Hind");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Khetbook • Page ${i}/${pages} • ${new Date().toLocaleString("en-IN")}`,
      14,
      290,
    );
  }
}

function nameOf(state: AppState, farmerId: string) {
  return state.farmers.find((f) => f.id === farmerId)?.name ?? "—";
}

function toolOf(state: AppState, toolId: string) {
  return state.tools.find((t) => t.id === toolId)?.nameHi ?? toolId;
}

/** Full export — all farmers, all entries, all payments, diesel, profit. */
export function exportFullLedgerPdf(state: AppState) {
  const doc = createPdfDoc();
  header(
    doc,
    state,
    "Complete Account Statement",
    `As of ${new Date().toLocaleDateString("en-IN")}`,
  );

  // Summary
  const totalEarn =
    state.entries.reduce((s, e) => s + e.cashReceived, 0) +
    state.payments.reduce((s, p) => s + p.amount, 0);
  const pendingTotal = state.farmers.reduce((s, f) => s + pendingForFarmer(state, f.id), 0);
  const fuelTotal = state.fuel.reduce((s, f) => s + f.amount, 0);

  autoTable(doc, {
    startY: 54,
    head: [["Summary", "Amount (INR)"]],
    body: [
      ["Total Earnings", fmtINR(totalEarn)],
      ["Pending Udhar", fmtINR(pendingTotal)],
      ["Total Diesel Expense", fmtINR(fuelTotal)],
      ["Net Profit (Earnings − Diesel)", fmtINR(totalEarn - fuelTotal)],
    ],
    theme: "grid",
    headStyles: { fillColor: [31, 138, 76] },
    styles: { font: "Hind" },
  });

  // Farmer-by-farmer
  for (const f of state.farmers) {
    const ents = state.entries.filter((e) => e.farmerId === f.id);
    const pays = state.payments.filter((p) => p.farmerId === f.id);
    if (!ents.length && !pays.length) continue;

    doc.addPage();
    header(doc, state, `Khata: ${f.name}`, f.phone ? `Phone: ${f.phone}` : undefined);

    autoTable(doc, {
      startY: 54,
      head: [["Date", "Tool", "Qty", "×", "Rate", "Total", "Cash", "Udhar", "Landowner"]],
      body: ents
        .slice()
        .sort((a, b) => +new Date(a.date) - +new Date(b.date))
        .map((e) => [
          fmtDate(e.date),
          toolOf(state, e.toolId),
          `${e.qty} ${e.unit}`,
          e.multiplier === "triple" ? "x3" : e.multiplier === "double" ? "x2" : "x1",
          fmtINR(e.rate),
          fmtINR(e.total),
          fmtINR(e.cashReceived),
          fmtINR(e.udharAdded),
          e.landowner || "self",
        ]),
      theme: "striped",
      headStyles: { fillColor: [31, 138, 76] },
      styles: { font: "Hind", fontSize: 8 },
    });

    if (pays.length) {
      autoTable(doc, {
        head: [["Payments Received", "Date", "Amount"]],
        body: pays
          .slice()
          .sort((a, b) => +new Date(a.date) - +new Date(b.date))
          .map((p, i) => [`#${i + 1}`, fmtDate(p.date), fmtINR(p.amount)]),
        theme: "grid",
        headStyles: { fillColor: [220, 100, 30] },
        styles: { font: "Hind" },
      });
    }

    const pending = pendingForFarmer(state, f.id);
    autoTable(doc, {
      body: [["Pending Balance", fmtINR(pending)]],
      theme: "plain",
      styles: { font: "Hind", fontSize: 12 },
    });
  }

  // Diesel
  if (state.fuel.length) {
    doc.addPage();
    header(doc, state, "Diesel Log");
    autoTable(doc, {
      startY: 54,
      head: [["Date", "Litres", "Rate (INR/L)", "Total", "Pump"]],
      body: state.fuel
        .slice()
        .sort((a, b) => +new Date(a.date) - +new Date(b.date))
        .map((f) => [
          fmtDate(f.date),
          f.litres?.toFixed(2) ?? "—",
          f.pricePerLitre ? fmtINR(f.pricePerLitre) : "—",
          fmtINR(f.amount),
          f.pumpName || "—",
        ]),
      theme: "striped",
      headStyles: { fillColor: [220, 100, 30] },
      styles: { font: "Hind" },
    });
  }

  footer(doc);
  doc.save(`khetbook-statement-${dayKey(new Date().toISOString())}.pdf`);
}

/** Per-farmer bill for a date range. */
export function exportFarmerBillPdf(
  state: AppState,
  farmerId: string,
  fromISO: string,
  toISO: string,
  rangeLabel: string,
) {
  const f = state.farmers.find((x) => x.id === farmerId);
  if (!f) return;
  const from = +new Date(fromISO);
  const to = +new Date(toISO);
  const ents = state.entries
    .filter((e) => e.farmerId === f.id)
    .filter((e) => {
      const t = +new Date(e.date);
      return t >= from && t <= to;
    })
    .sort((a, b) => +new Date(a.date) - +new Date(b.date));
  const pays = state.payments
    .filter((p) => p.farmerId === f.id)
    .filter((p) => {
      const t = +new Date(p.date);
      return t >= from && t <= to;
    })
    .sort((a, b) => +new Date(a.date) - +new Date(b.date));

  const doc = createPdfDoc();
  header(doc, state, `Bill: ${f.name}`, rangeLabel);

  autoTable(doc, {
    startY: 54,
    head: [["Date", "Work", "Qty", "Rate", "Total", "Paid", "Udhar", "Landowner"]],
    body: ents.map((e) => [
      fmtDate(e.date),
      `${toolOf(state, e.toolId)}${e.multiplier !== "single" ? ` (${e.multiplier === "double" ? "x2" : "x3"})` : ""}`,
      `${e.qty} ${e.unit}`,
      fmtINR(e.rate),
      fmtINR(e.total),
      fmtINR(e.cashReceived),
      fmtINR(e.udharAdded),
      e.landowner || "self",
    ]),
    foot: [
      [
        "",
        "",
        "",
        "Total",
        fmtINR(ents.reduce((s, e) => s + e.total, 0)),
        fmtINR(ents.reduce((s, e) => s + e.cashReceived, 0)),
        fmtINR(ents.reduce((s, e) => s + e.udharAdded, 0)),
        "",
      ],
    ],
    theme: "striped",
    headStyles: { fillColor: [31, 138, 76] },
    footStyles: { fillColor: [240, 240, 240], textColor: 20 },
    styles: { font: "Hind", fontSize: 9 },
  });

  if (pays.length) {
    autoTable(doc, {
      head: [["Payments Received", "Date", "Amount"]],
      body: pays.map((p, i) => [`#${i + 1}`, fmtDate(p.date), fmtINR(p.amount)]),
      theme: "grid",
      headStyles: { fillColor: [220, 100, 30] },
      styles: { font: "Hind" },
    });
  }

  const pending = pendingForFarmer(state, f.id);
  autoTable(doc, {
    body: [
      ["Current pending balance (all-time)", fmtINR(pending)],
      ["UPI", state.settings.upiVpa || "—"],
      ["Account holder", state.settings.merchantName || state.settings.userName || "—"],
    ],
    theme: "plain",
    styles: { font: "Hind", fontSize: 11 },
  });

  footer(doc);

  const blob = doc.output("blob");
  return new File(
    [blob],
    `khetbook-${f.name.replace(/\s+/g, "_")}-${dayKey(fromISO)}_${dayKey(toISO)}.pdf`,
    {
      type: "application/pdf",
    },
  );
}
