/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhataIndexRouteImport } from './routes/khata.index'
import { Route as KhataFarmerIdRouteImport } from './routes/khata.$farmerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataIndexRoute = KhataIndexRouteImport.update({
  id: '/khata/',
  path: '/khata/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataFarmerIdRoute = KhataFarmerIdRouteImport.update({
  id: '/khata/$farmerId',
  path: '/khata/$farmerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/khata/$farmerId': typeof KhataFarmerIdRoute
  '/khata/': typeof KhataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/khata/$farmerId': typeof KhataFarmerIdRoute
  '/khata': typeof KhataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/khata/$farmerId': typeof KhataFarmerIdRoute
  '/khata/': typeof KhataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/settings' | '/khata/$farmerId' | '/khata/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/settings' | '/khata/$farmerId' | '/khata'
  id:
    '__root__' | '/' | '/history' | '/settings' | '/khata/$farmerId' | '/khata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  KhataFarmerIdRoute: typeof KhataFarmerIdRoute
  KhataIndexRoute: typeof KhataIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata/': {
      id: '/khata/'
      path: '/khata'
      fullPath: '/khata/'
      preLoaderRoute: typeof KhataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata/$farmerId': {
      id: '/khata/$farmerId'
      path: '/khata/$farmerId'
      fullPath: '/khata/$farmerId'
      preLoaderRoute: typeof KhataFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  KhataFarmerIdRoute: KhataFarmerIdRoute,
  KhataIndexRoute: KhataIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
